/**
 * generated by Xtext 2.21.0
 */
package dk.chcla15.mathinterpreter;

import dk.chcla15.mathinterpreter.AbstractMathAssignmentLanguageRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MathAssignmentLanguageRuntimeModule extends AbstractMathAssignmentLanguageRuntimeModule {
}
