/*
 * generated by Xtext 2.21.0
 */
package dk.chcla15.mathinterpreter.validation


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class MathAssignmentLanguageValidator extends AbstractMathAssignmentLanguageValidator {
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MathAssignmentLanguagePackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	
}
