/*
 * generated by Xtext 2.21.0
 */
package dk.chcla15.mathinterpreter.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MathAssignmentLanguageGrammarAccess extends AbstractGrammarElementFinder {
	
	public class MathExpElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.chcla15.mathinterpreter.MathAssignmentLanguage.MathExp");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cResultKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cIsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cExpAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cExpExpParserRuleCall_2_0 = (RuleCall)cExpAssignment_2.eContents().get(0);
		
		//MathExp:
		//	'result' 'is' exp=Exp;
		@Override public ParserRule getRule() { return rule; }
		
		//'result' 'is' exp=Exp
		public Group getGroup() { return cGroup; }
		
		//'result'
		public Keyword getResultKeyword_0() { return cResultKeyword_0; }
		
		//'is'
		public Keyword getIsKeyword_1() { return cIsKeyword_1; }
		
		//exp=Exp
		public Assignment getExpAssignment_2() { return cExpAssignment_2; }
		
		//Exp
		public RuleCall getExpExpParserRuleCall_2_0() { return cExpExpParserRuleCall_2_0; }
	}
	public class ExpElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.chcla15.mathinterpreter.MathAssignmentLanguage.Exp");
		private final RuleCall cPlusMinusExpParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Exp:
		//	PlusMinusExp;
		@Override public ParserRule getRule() { return rule; }
		
		////Primary ({Exp.left=current} operator=ExpOp right=Primary)* // Left associativity by default
		//PlusMinusExp
		public RuleCall getPlusMinusExpParserRuleCall() { return cPlusMinusExpParserRuleCall; }
	}
	public class PlusMinusExpElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.chcla15.mathinterpreter.MathAssignmentLanguage.PlusMinusExp");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cMulOrDivExpParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cExpLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOperatorAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cOperatorPlusMinusOpParserRuleCall_1_1_0 = (RuleCall)cOperatorAssignment_1_1.eContents().get(0);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightMulOrDivExpParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//PlusMinusExp Exp:
		//	MulOrDivExp ({Exp.left=current} operator=PlusMinusOp right=MulOrDivExp)*;
		@Override public ParserRule getRule() { return rule; }
		
		//MulOrDivExp ({Exp.left=current} operator=PlusMinusOp right=MulOrDivExp)*
		public Group getGroup() { return cGroup; }
		
		//MulOrDivExp
		public RuleCall getMulOrDivExpParserRuleCall_0() { return cMulOrDivExpParserRuleCall_0; }
		
		//({Exp.left=current} operator=PlusMinusOp right=MulOrDivExp)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{Exp.left=current}
		public Action getExpLeftAction_1_0() { return cExpLeftAction_1_0; }
		
		//operator=PlusMinusOp
		public Assignment getOperatorAssignment_1_1() { return cOperatorAssignment_1_1; }
		
		//PlusMinusOp
		public RuleCall getOperatorPlusMinusOpParserRuleCall_1_1_0() { return cOperatorPlusMinusOpParserRuleCall_1_1_0; }
		
		//right=MulOrDivExp
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//MulOrDivExp
		public RuleCall getRightMulOrDivExpParserRuleCall_1_2_0() { return cRightMulOrDivExpParserRuleCall_1_2_0; }
	}
	public class MulOrDivExpElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.chcla15.mathinterpreter.MathAssignmentLanguage.MulOrDivExp");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cPrimaryParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cExpLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOperatorAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cOperatorMultDivOpParserRuleCall_1_1_0 = (RuleCall)cOperatorAssignment_1_1.eContents().get(0);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightPrimaryParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//MulOrDivExp Exp:
		//	Primary ({Exp.left=current} operator=MultDivOp right=Primary)*;
		@Override public ParserRule getRule() { return rule; }
		
		//Primary ({Exp.left=current} operator=MultDivOp right=Primary)*
		public Group getGroup() { return cGroup; }
		
		//Primary
		public RuleCall getPrimaryParserRuleCall_0() { return cPrimaryParserRuleCall_0; }
		
		//({Exp.left=current} operator=MultDivOp right=Primary)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{Exp.left=current}
		public Action getExpLeftAction_1_0() { return cExpLeftAction_1_0; }
		
		//operator=MultDivOp
		public Assignment getOperatorAssignment_1_1() { return cOperatorAssignment_1_1; }
		
		//MultDivOp
		public RuleCall getOperatorMultDivOpParserRuleCall_1_1_0() { return cOperatorMultDivOpParserRuleCall_1_1_0; }
		
		//right=Primary
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//Primary
		public RuleCall getRightPrimaryParserRuleCall_1_2_0() { return cRightPrimaryParserRuleCall_1_2_0; }
	}
	public class ExpOpElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.chcla15.mathinterpreter.MathAssignmentLanguage.ExpOp");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cMultDivOpParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cPlusMinusOpParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//ExpOp:
		//	MultDivOp | PlusMinusOp;
		@Override public ParserRule getRule() { return rule; }
		
		//MultDivOp | PlusMinusOp
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//MultDivOp
		public RuleCall getMultDivOpParserRuleCall_0() { return cMultDivOpParserRuleCall_0; }
		
		//PlusMinusOp
		public RuleCall getPlusMinusOpParserRuleCall_1() { return cPlusMinusOpParserRuleCall_1; }
	}
	public class MultDivOpElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.chcla15.mathinterpreter.MathAssignmentLanguage.MultDivOp");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cMultAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cAsteriskKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cDivAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cSolidusKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		
		//MultDivOp ExpOp:
		//	{Mult} '*' | {Div} '/';
		@Override public ParserRule getRule() { return rule; }
		
		//{Mult} '*' | {Div} '/'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{Mult} '*'
		public Group getGroup_0() { return cGroup_0; }
		
		//{Mult}
		public Action getMultAction_0_0() { return cMultAction_0_0; }
		
		//'*'
		public Keyword getAsteriskKeyword_0_1() { return cAsteriskKeyword_0_1; }
		
		//{Div} '/'
		public Group getGroup_1() { return cGroup_1; }
		
		//{Div}
		public Action getDivAction_1_0() { return cDivAction_1_0; }
		
		//'/'
		public Keyword getSolidusKeyword_1_1() { return cSolidusKeyword_1_1; }
	}
	public class PlusMinusOpElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.chcla15.mathinterpreter.MathAssignmentLanguage.PlusMinusOp");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cPlusAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cPlusSignKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cMinusAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		
		//PlusMinusOp ExpOp:
		//	{Plus} '+' | {Minus} '-';
		@Override public ParserRule getRule() { return rule; }
		
		//{Plus} '+' | {Minus} '-'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{Plus} '+'
		public Group getGroup_0() { return cGroup_0; }
		
		//{Plus}
		public Action getPlusAction_0_0() { return cPlusAction_0_0; }
		
		//'+'
		public Keyword getPlusSignKeyword_0_1() { return cPlusSignKeyword_0_1; }
		
		//{Minus} '-'
		public Group getGroup_1() { return cGroup_1; }
		
		//{Minus}
		public Action getMinusAction_1_0() { return cMinusAction_1_0; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_1_1() { return cHyphenMinusKeyword_1_1; }
	}
	public class PrimaryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.chcla15.mathinterpreter.MathAssignmentLanguage.Primary");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cNumberAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Assignment cValueAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cValueINTTerminalRuleCall_0_1_0 = (RuleCall)cValueAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cParenthesisAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cExpAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cExpExpParserRuleCall_1_2_0 = (RuleCall)cExpAssignment_1_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		
		//Primary Exp:
		//	{Number} value=INT | {Parenthesis} '(' exp=Exp ')';
		@Override public ParserRule getRule() { return rule; }
		
		//{Number} value=INT | {Parenthesis} '(' exp=Exp ')'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{Number} value=INT
		public Group getGroup_0() { return cGroup_0; }
		
		//{Number}
		public Action getNumberAction_0_0() { return cNumberAction_0_0; }
		
		//value=INT
		public Assignment getValueAssignment_0_1() { return cValueAssignment_0_1; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_0_1_0() { return cValueINTTerminalRuleCall_0_1_0; }
		
		//{Parenthesis} '(' exp=Exp ')'
		public Group getGroup_1() { return cGroup_1; }
		
		//{Parenthesis}
		public Action getParenthesisAction_1_0() { return cParenthesisAction_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_1() { return cLeftParenthesisKeyword_1_1; }
		
		//exp=Exp
		public Assignment getExpAssignment_1_2() { return cExpAssignment_1_2; }
		
		//Exp
		public RuleCall getExpExpParserRuleCall_1_2_0() { return cExpExpParserRuleCall_1_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_3() { return cRightParenthesisKeyword_1_3; }
	}
	
	
	private final MathExpElements pMathExp;
	private final ExpElements pExp;
	private final PlusMinusExpElements pPlusMinusExp;
	private final MulOrDivExpElements pMulOrDivExp;
	private final ExpOpElements pExpOp;
	private final MultDivOpElements pMultDivOp;
	private final PlusMinusOpElements pPlusMinusOp;
	private final PrimaryElements pPrimary;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MathAssignmentLanguageGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pMathExp = new MathExpElements();
		this.pExp = new ExpElements();
		this.pPlusMinusExp = new PlusMinusExpElements();
		this.pMulOrDivExp = new MulOrDivExpElements();
		this.pExpOp = new ExpOpElements();
		this.pMultDivOp = new MultDivOpElements();
		this.pPlusMinusOp = new PlusMinusOpElements();
		this.pPrimary = new PrimaryElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("dk.chcla15.mathinterpreter.MathAssignmentLanguage".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//MathExp:
	//	'result' 'is' exp=Exp;
	public MathExpElements getMathExpAccess() {
		return pMathExp;
	}
	
	public ParserRule getMathExpRule() {
		return getMathExpAccess().getRule();
	}
	
	//Exp:
	//	PlusMinusExp;
	public ExpElements getExpAccess() {
		return pExp;
	}
	
	public ParserRule getExpRule() {
		return getExpAccess().getRule();
	}
	
	//PlusMinusExp Exp:
	//	MulOrDivExp ({Exp.left=current} operator=PlusMinusOp right=MulOrDivExp)*;
	public PlusMinusExpElements getPlusMinusExpAccess() {
		return pPlusMinusExp;
	}
	
	public ParserRule getPlusMinusExpRule() {
		return getPlusMinusExpAccess().getRule();
	}
	
	//MulOrDivExp Exp:
	//	Primary ({Exp.left=current} operator=MultDivOp right=Primary)*;
	public MulOrDivExpElements getMulOrDivExpAccess() {
		return pMulOrDivExp;
	}
	
	public ParserRule getMulOrDivExpRule() {
		return getMulOrDivExpAccess().getRule();
	}
	
	//ExpOp:
	//	MultDivOp | PlusMinusOp;
	public ExpOpElements getExpOpAccess() {
		return pExpOp;
	}
	
	public ParserRule getExpOpRule() {
		return getExpOpAccess().getRule();
	}
	
	//MultDivOp ExpOp:
	//	{Mult} '*' | {Div} '/';
	public MultDivOpElements getMultDivOpAccess() {
		return pMultDivOp;
	}
	
	public ParserRule getMultDivOpRule() {
		return getMultDivOpAccess().getRule();
	}
	
	//PlusMinusOp ExpOp:
	//	{Plus} '+' | {Minus} '-';
	public PlusMinusOpElements getPlusMinusOpAccess() {
		return pPlusMinusOp;
	}
	
	public ParserRule getPlusMinusOpRule() {
		return getPlusMinusOpAccess().getRule();
	}
	
	//Primary Exp:
	//	{Number} value=INT | {Parenthesis} '(' exp=Exp ')';
	public PrimaryElements getPrimaryAccess() {
		return pPrimary;
	}
	
	public ParserRule getPrimaryRule() {
		return getPrimaryAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
