/*
 * generated by Xtext 2.21.0
 */
package dk.chcla15.mathinterpreter.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMathAssignmentLanguageScopeProvider extends DelegatingScopeProvider {
}
