/**
 * generated by Xtext 2.21.0
 */
package dk.chcla15.mathinterpreter.scoping;

import dk.chcla15.mathinterpreter.scoping.AbstractMathAssignmentLanguageScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class MathAssignmentLanguageScopeProvider extends AbstractMathAssignmentLanguageScopeProvider {
}
