/*
 * generated by Xtext 2.21.0
 */
package dk.chcla15.mathinterpreter


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MathAssignmentLanguageRuntimeModule extends AbstractMathAssignmentLanguageRuntimeModule {
}
