grammar dk.chcla15.mathinterpreter.MathAssignmentLanguage with org.eclipse.xtext.common.Terminals

generate mathAssignmentLanguage "http://www.chcla15.dk/mathinterpreter/MathAssignmentLanguage"

MathExp:
	'result' 'is' exp=Exp
;

Exp:
	//left=Primary (operator=ExpOp right=Exp)?
	Primary ({Exp.left=current} operator=ExpOp right=Primary)*
;

ExpOp:
	{Plus} '+' | {Minus} '-'	 | {Mult} '*' | {Div} '/'	
;

Primary returns Exp:
	{Number} value=INT |
	{Parenthesis} '(' exp=Exp ')'
;