grammar dk.chcla15.mathinterpreter.MathAssignmentLanguage with org.eclipse.xtext.common.Terminals

generate mathAssignmentLanguage "http://www.chcla15.dk/mathinterpreter/MathAssignmentLanguage"

MathExp:
	'result' 'is' exp=Exp
;

Exp: // Illegal due to left recursion
	left=Exp (operator=ExpOp right=Exp)?
;

ExpOp:
	{Plus} '+' | {Minus} '-'	 | {Mult} '*' | {Div} '/'	
;

Primary:
	Number | Parenthesis
;

Parenthesis:
	'(' exp=Exp ')'
;

Number:
	value=INT
;