/*
 * generated by Xtext 2.21.0
 */
package dk.chcla15.mathinterpreter.ide


/**
 * Use this class to register ide components.
 */
class MathAssignmentLanguageIdeModule extends AbstractMathAssignmentLanguageIdeModule {
}
