/*
 * generated by Xtext 2.21.0
 */
package dk.chcla15.mathinterpreter.tests

import com.google.inject.Inject
import dk.chcla15.mathinterpreter.mathAssignmentLanguage.MathExp
import dk.chcla15.mathinterpreter.mathAssignmentLanguage.Number
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import static extension org.junit.Assert.*;
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import dk.chcla15.mathinterpreter.mathAssignmentLanguage.Parenthesis

@ExtendWith(InjectionExtension)
@InjectWith(MathAssignmentLanguageInjectorProvider)
class MathAssignmentLanguageParsingTest {
	@Inject
	extension ParseHelper<MathExp> parseHelper
	
	@Test
	def void testParsingExpression() {
		"result is 10".parse.assertNotNull
	}
	
	@Test
	def void testPlusTwoNumbers() {
		'''
		result is 10+10
		'''.parse => [
			(exp.left as Number).value.assertEquals(10)			
			(exp.right as Number).value.assertEquals(10)
		]
	}
	
	@Test
	def void testLeftPlusParenthesis() {
		'''
		result is (2+1)+3
		'''.parse => [
			(exp.left as Parenthesis) => [
				(exp.left as Number).value.assertEquals(2)
				(exp.right as Number).value.assertEquals(1)
			]			
			(exp.right as Number).value.assertEquals(3)
		]
	}
	
	@Test
	def void testRightPlusParenthesis() {
		'''
		result is 2+(1+3)
		'''.parse => [		
			(exp.left as Number).value.assertEquals(2)
			(exp.right as Parenthesis) => [
				(exp.left as Number).value.assertEquals(1)
				(exp.right as Number).value.assertEquals(3)
			]	
		]
	}
}
