/**
 * generated by Xtext 2.21.0
 */
package dk.chcla15.mathinterpreter.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import dk.chcla15.mathinterpreter.MathAssignmentLanguageRuntimeModule;
import dk.chcla15.mathinterpreter.MathAssignmentLanguageStandaloneSetup;
import dk.chcla15.mathinterpreter.ide.MathAssignmentLanguageIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MathAssignmentLanguageIdeSetup extends MathAssignmentLanguageStandaloneSetup {
  @Override
  public Injector createInjector() {
    MathAssignmentLanguageRuntimeModule _mathAssignmentLanguageRuntimeModule = new MathAssignmentLanguageRuntimeModule();
    MathAssignmentLanguageIdeModule _mathAssignmentLanguageIdeModule = new MathAssignmentLanguageIdeModule();
    return Guice.createInjector(Modules2.mixin(_mathAssignmentLanguageRuntimeModule, _mathAssignmentLanguageIdeModule));
  }
}
