/**
 * generated by Xtext 2.21.0
 */
package dk.chcla15.mathinterpreter.ide;

import dk.chcla15.mathinterpreter.ide.AbstractMathAssignmentLanguageIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MathAssignmentLanguageIdeModule extends AbstractMathAssignmentLanguageIdeModule {
}
