/*
 * generated by Xtext 2.21.0
 */
package dk.chcla15.mathinterpreter.ui.tests;

import com.google.inject.Injector;
import dk.chcla15.mathinterpreter.ui.internal.MathinterpreterActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MathAssignmentLanguageUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MathinterpreterActivator.getInstance().getInjector("dk.chcla15.mathinterpreter.MathAssignmentLanguage");
	}

}
