/**
 * generated by Xtext 2.21.0
 */
package dk.chcla15.mathinterpreter.ui;

import dk.chcla15.mathinterpreter.ui.AbstractMathAssignmentLanguageUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MathAssignmentLanguageUiModule extends AbstractMathAssignmentLanguageUiModule {
  public MathAssignmentLanguageUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
