/*
 * generated by Xtext 2.21.0
 */
package dk.chcla15.mathinterpreter.parser.antlr;

import com.google.inject.Inject;
import dk.chcla15.mathinterpreter.parser.antlr.internal.InternalMathAssignmentLanguageParser;
import dk.chcla15.mathinterpreter.services.MathAssignmentLanguageGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MathAssignmentLanguageParser extends AbstractAntlrParser {

	@Inject
	private MathAssignmentLanguageGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMathAssignmentLanguageParser createParser(XtextTokenStream stream) {
		return new InternalMathAssignmentLanguageParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "MathExp";
	}

	public MathAssignmentLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MathAssignmentLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
