/*
 * generated by Xtext 2.21.0
 */
package dk.chcla15.mathinterpreter.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MathAssignmentLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("dk/chcla15/mathinterpreter/parser/antlr/internal/InternalMathAssignmentLanguage.tokens");
	}
}
