/**
 * generated by Xtext 2.21.0
 */
package dk.chcla15.mathinterpreter.mathAssignmentLanguage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.MathAssignmentLanguageFactory
 * @model kind="package"
 * @generated
 */
public interface MathAssignmentLanguagePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "mathAssignmentLanguage";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.chcla15.dk/mathinterpreter/MathAssignmentLanguage";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "mathAssignmentLanguage";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MathAssignmentLanguagePackage eINSTANCE = dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MathAssignmentLanguagePackageImpl.init();

  /**
   * The meta object id for the '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MathExpImpl <em>Math Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MathExpImpl
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MathAssignmentLanguagePackageImpl#getMathExp()
   * @generated
   */
  int MATH_EXP = 0;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATH_EXP__EXP = 0;

  /**
   * The number of structural features of the '<em>Math Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATH_EXP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.ExpImpl <em>Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.ExpImpl
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MathAssignmentLanguagePackageImpl#getExp()
   * @generated
   */
  int EXP = 1;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP__LEFT = 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP__OPERATOR = 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP__RIGHT = 2;

  /**
   * The number of structural features of the '<em>Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.ExpOpImpl <em>Exp Op</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.ExpOpImpl
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MathAssignmentLanguagePackageImpl#getExpOp()
   * @generated
   */
  int EXP_OP = 2;

  /**
   * The number of structural features of the '<em>Exp Op</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_OP_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.PlusImpl <em>Plus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.PlusImpl
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MathAssignmentLanguagePackageImpl#getPlus()
   * @generated
   */
  int PLUS = 3;

  /**
   * The number of structural features of the '<em>Plus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS_FEATURE_COUNT = EXP_OP_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MinusImpl <em>Minus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MinusImpl
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MathAssignmentLanguagePackageImpl#getMinus()
   * @generated
   */
  int MINUS = 4;

  /**
   * The number of structural features of the '<em>Minus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS_FEATURE_COUNT = EXP_OP_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MultImpl <em>Mult</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MultImpl
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MathAssignmentLanguagePackageImpl#getMult()
   * @generated
   */
  int MULT = 5;

  /**
   * The number of structural features of the '<em>Mult</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT_FEATURE_COUNT = EXP_OP_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.DivImpl <em>Div</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.DivImpl
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MathAssignmentLanguagePackageImpl#getDiv()
   * @generated
   */
  int DIV = 6;

  /**
   * The number of structural features of the '<em>Div</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV_FEATURE_COUNT = EXP_OP_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.NumberImpl <em>Number</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.NumberImpl
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MathAssignmentLanguagePackageImpl#getNumber()
   * @generated
   */
  int NUMBER = 7;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER__LEFT = EXP__LEFT;

  /**
   * The feature id for the '<em><b>Operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER__OPERATOR = EXP__OPERATOR;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER__RIGHT = EXP__RIGHT;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER__VALUE = EXP_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Number</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_FEATURE_COUNT = EXP_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.ParenthesisImpl <em>Parenthesis</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.ParenthesisImpl
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MathAssignmentLanguagePackageImpl#getParenthesis()
   * @generated
   */
  int PARENTHESIS = 8;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARENTHESIS__LEFT = EXP__LEFT;

  /**
   * The feature id for the '<em><b>Operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARENTHESIS__OPERATOR = EXP__OPERATOR;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARENTHESIS__RIGHT = EXP__RIGHT;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARENTHESIS__EXP = EXP_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Parenthesis</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARENTHESIS_FEATURE_COUNT = EXP_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.MathExp <em>Math Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Math Exp</em>'.
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.MathExp
   * @generated
   */
  EClass getMathExp();

  /**
   * Returns the meta object for the containment reference '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.MathExp#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.MathExp#getExp()
   * @see #getMathExp()
   * @generated
   */
  EReference getMathExp_Exp();

  /**
   * Returns the meta object for class '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.Exp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exp</em>'.
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.Exp
   * @generated
   */
  EClass getExp();

  /**
   * Returns the meta object for the containment reference '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.Exp#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.Exp#getLeft()
   * @see #getExp()
   * @generated
   */
  EReference getExp_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.Exp#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Operator</em>'.
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.Exp#getOperator()
   * @see #getExp()
   * @generated
   */
  EReference getExp_Operator();

  /**
   * Returns the meta object for the containment reference '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.Exp#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.Exp#getRight()
   * @see #getExp()
   * @generated
   */
  EReference getExp_Right();

  /**
   * Returns the meta object for class '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.ExpOp <em>Exp Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exp Op</em>'.
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.ExpOp
   * @generated
   */
  EClass getExpOp();

  /**
   * Returns the meta object for class '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.Plus <em>Plus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Plus</em>'.
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.Plus
   * @generated
   */
  EClass getPlus();

  /**
   * Returns the meta object for class '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.Minus <em>Minus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Minus</em>'.
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.Minus
   * @generated
   */
  EClass getMinus();

  /**
   * Returns the meta object for class '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.Mult <em>Mult</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mult</em>'.
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.Mult
   * @generated
   */
  EClass getMult();

  /**
   * Returns the meta object for class '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.Div <em>Div</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Div</em>'.
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.Div
   * @generated
   */
  EClass getDiv();

  /**
   * Returns the meta object for class '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.Number <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Number</em>'.
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.Number
   * @generated
   */
  EClass getNumber();

  /**
   * Returns the meta object for the attribute '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.Number#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.Number#getValue()
   * @see #getNumber()
   * @generated
   */
  EAttribute getNumber_Value();

  /**
   * Returns the meta object for class '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.Parenthesis <em>Parenthesis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parenthesis</em>'.
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.Parenthesis
   * @generated
   */
  EClass getParenthesis();

  /**
   * Returns the meta object for the containment reference '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.Parenthesis#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.Parenthesis#getExp()
   * @see #getParenthesis()
   * @generated
   */
  EReference getParenthesis_Exp();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MathAssignmentLanguageFactory getMathAssignmentLanguageFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MathExpImpl <em>Math Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MathExpImpl
     * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MathAssignmentLanguagePackageImpl#getMathExp()
     * @generated
     */
    EClass MATH_EXP = eINSTANCE.getMathExp();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MATH_EXP__EXP = eINSTANCE.getMathExp_Exp();

    /**
     * The meta object literal for the '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.ExpImpl <em>Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.ExpImpl
     * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MathAssignmentLanguagePackageImpl#getExp()
     * @generated
     */
    EClass EXP = eINSTANCE.getExp();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXP__LEFT = eINSTANCE.getExp_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXP__OPERATOR = eINSTANCE.getExp_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXP__RIGHT = eINSTANCE.getExp_Right();

    /**
     * The meta object literal for the '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.ExpOpImpl <em>Exp Op</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.ExpOpImpl
     * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MathAssignmentLanguagePackageImpl#getExpOp()
     * @generated
     */
    EClass EXP_OP = eINSTANCE.getExpOp();

    /**
     * The meta object literal for the '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.PlusImpl <em>Plus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.PlusImpl
     * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MathAssignmentLanguagePackageImpl#getPlus()
     * @generated
     */
    EClass PLUS = eINSTANCE.getPlus();

    /**
     * The meta object literal for the '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MinusImpl <em>Minus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MinusImpl
     * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MathAssignmentLanguagePackageImpl#getMinus()
     * @generated
     */
    EClass MINUS = eINSTANCE.getMinus();

    /**
     * The meta object literal for the '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MultImpl <em>Mult</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MultImpl
     * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MathAssignmentLanguagePackageImpl#getMult()
     * @generated
     */
    EClass MULT = eINSTANCE.getMult();

    /**
     * The meta object literal for the '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.DivImpl <em>Div</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.DivImpl
     * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MathAssignmentLanguagePackageImpl#getDiv()
     * @generated
     */
    EClass DIV = eINSTANCE.getDiv();

    /**
     * The meta object literal for the '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.NumberImpl <em>Number</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.NumberImpl
     * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MathAssignmentLanguagePackageImpl#getNumber()
     * @generated
     */
    EClass NUMBER = eINSTANCE.getNumber();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBER__VALUE = eINSTANCE.getNumber_Value();

    /**
     * The meta object literal for the '{@link dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.ParenthesisImpl <em>Parenthesis</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.ParenthesisImpl
     * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl.MathAssignmentLanguagePackageImpl#getParenthesis()
     * @generated
     */
    EClass PARENTHESIS = eINSTANCE.getParenthesis();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARENTHESIS__EXP = eINSTANCE.getParenthesis_Exp();

  }

} //MathAssignmentLanguagePackage
