/**
 * generated by Xtext 2.21.0
 */
package dk.chcla15.mathinterpreter.mathAssignmentLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mult</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.chcla15.mathinterpreter.mathAssignmentLanguage.MathAssignmentLanguagePackage#getMult()
 * @model
 * @generated
 */
public interface Mult extends ExpOp
{
} // Mult
