/**
 * generated by Xtext 2.21.0
 */
package dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl;

import dk.chcla15.mathinterpreter.mathAssignmentLanguage.ExpOp;
import dk.chcla15.mathinterpreter.mathAssignmentLanguage.MathAssignmentLanguagePackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Exp Op</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExpOpImpl extends MinimalEObjectImpl.Container implements ExpOp
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExpOpImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MathAssignmentLanguagePackage.Literals.EXP_OP;
  }

} //ExpOpImpl
