/**
 * generated by Xtext 2.21.0
 */
package dk.chcla15.mathinterpreter.mathAssignmentLanguage.impl;

import dk.chcla15.mathinterpreter.mathAssignmentLanguage.MathAssignmentLanguagePackage;
import dk.chcla15.mathinterpreter.mathAssignmentLanguage.Primary;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Primary</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PrimaryImpl extends MinimalEObjectImpl.Container implements Primary
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PrimaryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MathAssignmentLanguagePackage.Literals.PRIMARY;
  }

} //PrimaryImpl
