/**
 * generated by Xtext 2.21.0
 */
package dk.chcla15.mathinterpreter.ui.contentassist;

import dk.chcla15.mathinterpreter.ui.contentassist.AbstractMathAssignmentLanguageProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MathAssignmentLanguageProposalProvider extends AbstractMathAssignmentLanguageProposalProvider {
}
