/**
 * generated by Xtext 2.21.0
 */
package dk.chcla15.mathinterpreter.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class MathAssignmentLanguageQuickfixProvider extends DefaultQuickfixProvider {
}
