/*
 * generated by Xtext 2.21.0
 */
package dk.chcla15.mathinterpreter.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractMathAssignmentLanguageValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(dk.chcla15.mathinterpreter.mathAssignmentLanguage.MathAssignmentLanguagePackage.eINSTANCE);
		return result;
	}
}
